name: Run UI and API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies (Frontend)
        run: npm install
        working-directory: frontend

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: frontend

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Start backend server
        working-directory: ./backend
        run: node app.js &


      - name: Wait for backend to be ready
        run: sleep 10

      - name: Install Newman
        run: npm install -g newman

      - name: Run API Tests via Postman
        run: newman run API_Collection.json
        

      - name: Run UI Tests (Playwright)
        run: npm run test:ui
        working-directory: frontend

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report/
